[tool.black]
line-length = 99
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
    \.idea

  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests
)/
'''
